import React from "react";
import {
  FaHtml5,
  FaCss3Alt,
  FaJava,
  FaPython,
  FaRust,
  FaPhp,
  FaReact,
  FaBootstrap,
  FaWordpress,
  FaVuejs,
  FaSass,
  FaNodeJs,
  FaGit,
  FaGithub,
  FaDocker,
  FaJs,
  FaNpm,
} from "react-icons/fa";
import {
  SiC,
  SiRuby,
  SiFlutter,
  SiLua,
  SiGo,
  SiFlask,
  SiBlender,
  SiSvelte,
  SiSqlite,
  SiMysql,
  SiPostgresql,
  SiGraphql,
  SiMongodb,
  SiOracle,
  SiRedux,
  SiRedis,
  SiCplusplus,
  SiCsharp,
  SiThreedotjs,
  SiDotnet,
  SiTailwindcss,
  SiTypescript,
  SiVisualstudiocode,
  SiVisualstudio,
  SiMicrosoftsqlserver,
  SiUnrealengine,
  SiUnity,
  SiGodotengine,
} from "react-icons/si";

export default function skillNameToImageSource(nombreSkill) {
  nombreSkill = nombreSkill.toLowerCase();

  const iconMap = {
    html: FaHtml5,
    css: FaCss3Alt,
    java: FaJava,
    c: SiC,
    python: FaPython,
    rust: FaRust,
    ruby: SiRuby,
    flutter: SiFlutter,
    php: FaPhp,
    lua: SiLua,
    go: SiGo,
    react: FaReact,
    flask: SiFlask,
    bootstrap: FaBootstrap,
    blender: SiBlender,
    wordpress: FaWordpress,
    vue: FaVuejs,
    svelte: SiSvelte,
    sqlite: SiSqlite,
    mysql: SiMysql,
    postgresql: SiPostgresql,
    graphql: SiGraphql,
    mongodb: SiMongodb,
    oracle: SiOracle,
    sass: FaSass,
    redux: SiRedux,
    redis: SiRedis,
    nodejs: FaNodeJs,
    git: FaGit,
    github: FaGithub,
    docker: FaDocker,
    js: FaJs,
    javascript: FaJs,
    "c++": SiCplusplus,
    cplusplus: SiCplusplus,
    "c#": SiCsharp,
    csharp: SiCsharp,
    three: SiThreedotjs,
    threejs: SiThreedotjs,
    ".net": SiDotnet,
    dotnet: SiDotnet,
    tailwinds: SiTailwindcss,
    tailwindscss: SiTailwindcss,
    ts: SiTypescript,
    typescript: SiTypescript,
    "type script": SiTypescript,
    vscode: SiVisualstudiocode,
    "visual studio code": SiVisualstudiocode,
    vsc: SiVisualstudiocode,
    vs: SiVisualstudio,
    "visual studio": SiVisualstudio,
    microsoftsqlserver: SiMicrosoftsqlserver,
    "microsoft sql server": SiMicrosoftsqlserver,
    unrealengine: SiUnrealengine,
    "unreal engine": SiUnrealengine,
    unreal: SiUnrealengine,
    unityengine: SiUnity,
    "unity engine": SiUnity,
    unity: SiUnity,
    godot: SiGodotengine,
    "godot engine": SiGodotengine,
    npm: FaNpm,
  };

  const Icon = iconMap[nombreSkill];
  return Icon ? <Icon /> : null;
}
